- name: Copy Orchestrator configuration file
  template:
    src: orchestrator.conf.json.j2
    dest: /etc/orchestrator.conf.json
    owner: root
    group: root
    mode: '0644'

- name : restart orchestrator 
  service:
    name: orchestrator.service
    state: restarted