---
- name: Modifier le fichier /etc/hostname
  ansible.builtin.lineinfile:
    path: /etc/hostname
    line: "{{ hostname_dns_roubaix }}"
    create: yes

- name: Modifier le fichier /etc/hosts pour le nouveau nom d'hôte
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1   {{ hostname_dns_roubaix }}"

- name: Appliquer le changement du nom d'hôte
  ansible.builtin.command:
    cmd: hostnamectl set-hostname "{{ hostname_dns_roubaix }}"

- name: Redémarrer le système (si nécessaire) pour appliquer le nom d'hôte
  ansible.builtin.reboot:
    msg: "Redémarrage nécessaire pour appliquer le nom d'hôte"
    pre_reboot_delay: 0
    post_reboot_delay: 10
    reboot_timeout: 300
    test_command: whoami
  when: hostname_dns_roubaix != "localhost"  # Conditionner si nécessaire
