---
- name: Installer Git sur une machine Debian/Ubuntu
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes


- name: Cloner un dépôt Git
  ansible.builtin.git:
    repo: 'https://github.com/Thoinoo/mspr_nester_dashboard.git'   # URL du dépôt Git
    dest: "{{ dashboard_path }}"                     # Chemin où cloner le dépôt
    clone: yes                                                 # Cloner le dépôt s'il n'existe pas
    update: yes                                                # Mettre à jour le dépôt si il existe déjà
    version: 'main'   

- name: Vérifier si Python est installé
  ansible.builtin.command:
    cmd: python3 --version
  register: python_installed
  ignore_errors: yes

- name: Installer Python3 si nécessaire
  ansible.builtin.apt:
    name: python3
    state: present
  when: python_installed.rc != 0

- name: Vérifier si pip est installé
  ansible.builtin.command:
    cmd: python3 -m pip --version
  register: pip_installed
  ignore_errors: yes

- name: Installer pip si nécessaire
  ansible.builtin.apt:
    name: python3-pip
    state: present
  when: pip_installed.rc != 0

- name: Créer un environnement virtuel Python (si nécessaire)
  ansible.builtin.command:
    cmd: python3 -m venv /chemin/vers/ton/projet/venv
  args:
    creates: /chemin/vers/ton/projet/venv

- name: Installer les dépendances Python depuis requirements.txt
  ansible.builtin.pip:
    requirements: /chemin/vers/ton/projet/requirements.txt
    virtualenv: /chemin/vers/ton/projet/venv
