---    
- name: copier .my.cnf 
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf

- name: copier mysql.cnf
  ansible.builtin.template:
    src: mysql.cnf.j2
    dest: /etc/mysql/conf.d/mysql.cnf

- name: restart mysql
  service:
    name: mysql 
    state: restarted



- name: Créer un utilisateur pour orchestrator
  ansible.builtin.mysql_user:
    name: "{{ orchestrator_user }}"
    password: "{{ orchestrator_password }}"
    host: "%"
    priv: "*.*:ALL"
    column_case_sensitive: false
    state: present
    config_file: "/root/.my.cnf"
    login_host: "localhost"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Créer un utilisateur pour la replication
  ansible.builtin.mysql_user:
    name: "{{ replication_user }}"
    password: "{{ replication_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    column_case_sensitive: false
    state: present
    config_file: "/root/.my.cnf"
    login_host: "localhost"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
  when: inventory_hostname in groups['nester_db_master']


- name: Créer une base de données orchestrator
  ansible.builtin.mysql_db:
    name: "orchestrator"
    state: present
    config_file: "/root/.my.cnf"
    login_host: "localhost"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
  when: inventory_hostname in groups['nester_db_master']

- name: Créer une base de données MySQL
  ansible.builtin.mysql_db:
    name: "{{ db_name }}"
    state: present
    config_file: "/root/.my.cnf"
    login_host: "localhost"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
  when: inventory_hostname in groups['nester_db_master']

- name: Créer un utilisateur MySQL
  ansible.builtin.mysql_user:
    name: "{{ user_db }}"
    password: "{{ user_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    column_case_sensitive: false
    state: present
    config_file: "/root/.my.cnf"
    login_host: "localhost"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"


