---    
- name: copier .my.cnf 
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf

- name: copier ansible.cnf
  ansible.builtin.copy:
    src: ansible.cnf
    dest: /etc/mysql/conf.d/ansible.cnf

- name: Redémarrer le service MySQL pour appliquer les modifications
  ansible.builtin.systemd:
    name: mysql
    state: restarted


# 2. Créer une base de données MySQL
- name: Créer une base de données MySQL
  ansible.builtin.mysql_db:
    name: "{{ db_name }}"
    state: present
    config_file: "/root/.my.cnf"
    login_host: "localhost"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Créer un utilisateur MySQL
  ansible.builtin.mysql_user:
    name: "{{ user_db }}"
    password: "{{ user_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    column_case_sensitive: false
    state: present
    config_file: "/root/.my.cnf"
    login_host: "localhost"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"


