---
- name: Copier le fichier mysql-apt-config sur le serveur
  ansible.builtin.copy:
    src: mysql-apt-config_0.8.33-1_all.deb
    dest: /tmp/mysql-apt-config_0.8.33-1_all.deb

- name: Installer le fichier .deb mysql-apt-config
  ansible.builtin.apt:
    deb: /tmp/mysql-apt-config_0.8.33-1_all.deb
    state: present

- name: Mettre à jour le cache APT après l'ajout du dépôt
  ansible.builtin.apt:
    update_cache: yes

- name: Installer MySQL Server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Installer MySQL client
  ansible.builtin.apt:
    name: mysql-client
    state: present

- name: Installer libmysqlclient-dev
  ansible.builtin.apt:
    name: libmysqlclient-dev
    state: present

- name: Nettoyer le fichier .deb téléchargé
  ansible.builtin.file:
    path: /tmp/mysql-apt-config_0.8.33-1_all.deb
    state: absent


- name: Installer pymysql avec apt
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

# - name: Installer mysqldb
#   ansible.builtin.apt:
#     name: python3-mysqldb
#     state: present



