---
- name: install ufw
  apt:
    name: ufw
    state: present 

- name: config ufw 
  command:
    cmd: "{{ item }}"
  loop:
    - "ufw allow proto tcp from {{ ansible_default_ipv4.address }} to any port 22"
    - "ufw allow 21114:21119/tcp"
    - "ufw allow 8000/tcp"
    - "ufw allow 21116/udp"
   # - "ufw enable"

- name: copie install.sh 
  copy: 
    src: install.sh 
    dest: /home/ansible/install.sh
    mode: 755


- name: install server 
  command: 
    argv: 
      - /home/ansible/install.sh 
      - --resolvedns
      - "{{ ansible_default_ipv4.address }}"
      - --skip-http
      - "true"