---
- name: Installer le paquet bind9
  apt:
    name: bind9
    state: present
    update_cache: yes

- name: Installer les outils de gestion BIND9
  apt:
    name: bind9utils
    state: present

- name: Installer le paquet resolvconf
  apt:
    name: resolvconf
    state: present

- name: Activer et démarrer le service bind9
  systemd:
    name: bind9
    enabled: yes
    state: started

- name: Copier le fichier de configuration BIND9 (named.conf.options)
  copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: '0644'

- name: Copier le fichier de configuration BIND9 (named.conf.local)
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: '0644'

- name: Copier la zone DNS db.nfl-it.local
  template:
    src: db.nfl-it.local.j2
    dest: /var/lib/bind/db.nfl-it.local
    owner: bind
    group: bind
    mode: '0644'

- name: Copier la zone DNS db.10
  template:
    src: db.10.j2
    dest: /var/lib/bind/db.10
    owner: bind
    group: bind
    mode: '0644'

# - name: Find all files in /var/lib/bind
#   ansible.builtin.find:
#     paths: /var/lib/bind
#     recurse: yes
#     file_type: file
#   register: bind_files

# - name: set ownership for Bind
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     owner: bind
#     group: bind
#     mode: '0644'
#   loop: "{{ bind_files.files }}"
#   when: bind_files.matched > 0

- name: Vérifier la configuration de Bind9
  command: named-checkconf
  register: check_config
  failed_when: check_config.rc != 0
  changed_when: false

- name: Vérifier la zone DNS
  command: named-checkzone zone.local /etc/bind/db.nfl-it.local
  register: check_zone
  failed_when: check_zone.rc != 0
  changed_when: false

- name: Redémarrer Bind9 pour appliquer les configurations
  systemd:
    name: bind9
    state: restarted

