hosts:
  - name: ns1
    ip: 10.0.0.2
    rev: 2.0.0
  - name: ns2
    ip: 10.1.0.2
    rev: 2.0.1
  - name: gitlab
    ip: 10.1.0.10
    rev: 10.0.1
  - name: pfsenserooubaix
    ip: 10.1.0.1
    rev: 1.0.1

### NESTER
  - name: nester
    ip: 10.1.0.50
    rev: 50.0.1
  - name: nester-api
    ip: 10.1.0.60
    rev: 60.0.1
  - name: nester-db
    ip: 10.1.0.71
    rev: 71.0.1

  - name: glpi
    ip: 10.0.0.102
    rev: 102.0.0
    
  - name: centreon
    ip: 10.0.0.101
    rev: 101.0.0
