hosts:
  - name: ns1
    ip: 10.0.0.2
    rev: 2.0.0
  - name: ns2
    ip: 10.1.0.2
    rev: 2.0.1
  - name: nester
    ip: 10.1.0.50
    rev: 12.0.1
  - name: gitlab
    ip: 10.1.0.10
    rev: 10.0.1
  - name: pfsenserooubaix
    ip: 10.1.0.1
    rev: 1.0.1
