---
- name: hostname config
  hosts: nester_back
  user: ansible
  become: true
  vars_files:
    - "../roles/nester_db/vars/main.yml" 
    - "../roles/nester_back/vars/keepalived.yml"
  roles:
    - ../roles/nester_back