---
- name: hostname config
  hosts: nester_db
  user: ansible
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../roles/orchestrator/vars/main.yml
  roles:
    - ../roles/nester_db