---
- name: ntp client install
  hosts: rsyslog_client
  user: ansible
  become: true
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  # vars_files:
  #   - ../roles/orchestrator/vars/main.yml
  roles:
    - ../roles/ntp_client