---
- name: Install tuto
  hosts: linux
  user: ansible
  become: true

  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        state: latest
 
    - name: install vim
      ansible.builtin.apt:
        name: vim
        state: absent
